In [1]:
import numpy as np

In [ ]:
1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [2]:
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [3]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [4]:
a = np.zeros((5,5))
a[1:,:-1:] = np.diag([1,2,3,4])
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [ ]:
4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [5]:
a = np.random.random((5, 5))
a = a - a.mean(axis=1).reshape(-1,1)
print(a.mean(axis=1))

[ 4.44089210e-17  0.00000000e+00  6.66133815e-17  2.22044605e-17
 -6.66133815e-17]


In [ ]:
5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [6]:
a = np.random.random((10, 3))
b = a[np.arange(10), np.abs(a - 0.5).argmin(axis=1)]
print(b)

[0.43975028 0.38160161 0.55334547 0.60632935 0.44721818 0.16616117
 0.32622852 0.33666406 0.67396409 0.44730585]


In [ ]:
6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [7]:
a = np.random.random((6, 6))
b = a.sum(axis=1)/a.max(axis=0)
print(b)

[3.12086477 2.96638415 3.89104295 1.84403967 7.74117489 2.03952013]


In [ ]:
7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [8]:
a = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
a[1:][(a == 0)[:-1]].max()

5

In [ ]:
8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [9]:
x = np.ones(10, dtype = 'int')
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += (i.reshape(len(i), 1) == np.arange(len(x))).sum(axis=0)
print(x)

[2 2 2 2 1 4 1 1 2 1]


In [ ]:
9. Задайте два массива
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и
b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [12]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])
c = b[np.argmin(abs(a.reshape(3,3,1) - b.reshape(1,1,4)), axis = 2)]
print(c)

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


In [ ]:
10. Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [11]:
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])
ma = np.convolve(a, np.ones(3)/3, mode='valid')
print(ma)

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]
